### PR TITLE
Implemented issues and bug fixes

### PR DESCRIPTION
**Pull request by Jubeki**
I love the Framework jigsaw. tailwind.jss is also simple and straight.
Issue #6 #9 #10 #12 are implemented but they are not perfect. so if you have improvements just add them.

### CODE REVIEW

**Comment by Jubeki** [comment]
@minthemiddle 
The pull request is still being ignored :(
Maybe something will help you.

**Comment by minthemiddle** [comment]
Sorry, it's just because the Travis build is still not fixed and would need to replicate your changes locally first or fix Travis first. Let me go the easy way and test it locally and then accept your PR…

**Comment by minthemiddle** [comment]
@Jubeki Done, sorry for the delay!

**Comment by Jubeki** [comment]
Thank you and no problem 👍

**Pull request merged**
